/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wsd_disambiguator_MblDisambiguator */

#ifndef _Included_wsd_disambiguator_MblDisambiguator
#define _Included_wsd_disambiguator_MblDisambiguator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wsd_disambiguator_MblDisambiguator
 * Method:    getAnswer
 * Signature: (Ljava/lang/String;[Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_wsd_disambiguator_MblDisambiguator_getAnswer
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
